export const LOCATIONS_DATA = [
  { value: "berlin", label: "Berlin" },
  { value: "braunschweig", label: "Braunschweig" },
  { value: "bremen", label: "Bremen" },
  { value: "bremerhaven", label: "Bremerhaven" },
  { value: "cottbus", label: "Cottbus" },
  { value: "dresden", label: "Dresden" },
  { value: "duesseldorf", label: "Düsseldorf" },
  { value: "erfurt", label: "Erfurt" },
  { value: "frankfurt-am-main", label: "Frankfurt am Main" },
  { value: "halle-saale", label: "Halle (Saale)" },
  { value: "hamburg", label: "Hamburg" },
  { value: "hannover", label: "Hannover" },
  { value: "jena", label: "Jena" },
  { value: "karlsruhe", label: "Karlsruhe" },
  { value: "kiel", label: "Kiel" },
  { value: "koeln", label: "Köln" },
  { value: "leipzig", label: "Leipzig" },
  { value: "luebeck", label: "Lübeck" },
  { value: "ludwigshafen-am-rhein", label: "Ludwigshafen am Rhein" },
  { value: "magdeburg", label: "Magdeburg" },
  { value: "mainz", label: "Mainz" },
  { value: "muenchen", label: "München" },
  { value: "neunkirchen", label: "Neunkirchen" },
  { value: "nuernberg", label: "Nürnberg" },
  { value: "potsdam", label: "Potsdam" },
  { value: "rostock", label: "Rostock" },
  { value: "saarbruecken", label: "Saarbrücken" },
  { value: "schwerin", label: "Schwerin" },
  { value: "stuttgart", label: "Stuttgart" },
  { value: "wiesbaden", label: "Wiesbaden" },
];

export const JOB_SITES = [
  { value: "StepStone", label: "StepStone" },
  { value: "LinkedIn", label: "LinkedIn" },
  { value: "Xing", label: "Xing" },
  { value: "Jobware", label: "Jobware" },
  { value: "Jooble", label: "Jooble" },
  { value: "Stellenanzeigen.de", label: "Stellenanzeigen.de" },
];

export const DISCIPLINES = [
  { value: "IT", label: "IT" },
  { value: "Marketing", label: "Marketing" },
  { value: "Vertrieb und Verkauf", label: "Vertrieb und Verkauf" },
  { value: "Medien", label: "Medien" },
  { value: "Bildung", label: "Bildung" },
  { value: "Beratung", label: "Beratung" },
  { value: "Management", label: "Management" },
  { value: "Administration", label: "Administration" },
  { value: "Personal", label: "Personal" },
  { value: "Buchhaltung", label: "Buchhaltung" },
  { value: "Ingenieurwesen", label: "Ingenieurwesen" },
  { value: "Kundenservice", label: "Kundenservice" },
  { value: "Finanzen", label: "Finanzen" },
  { value: "Logistik", label: "Logistik" },
  { value: "Wissenschaften", label: "Wissenschaften" },
  { value: "Bauwesen", label: "Bauwesen" },
  { value: "Banken", label: "Banken" },
  { value: "Gastronomie, Hotellerie", label: "Gastronomie, Hotellerie" },
  { value: "Gesundheit", label: "Gesundheit" },
  { value: "Groß- und Einzelhandel", label: "Groß- und Einzelhandel" },
];

export const SKILLS = [
  { value: "agile", label: "Agile Methoden" },
  { value: "angular", label: "Angular" },
  { value: "ansible", label: "Ansible" },
  { value: "aws-advanced", label: "AWS Vertiefung (EC2, S3, Lambda, RDS etc.)" },
  { value: "azure-advanced", label: "Azure Vertiefung (VMs, Blob Storage, Functions etc.)" },
  { value: "big-data-tech", label: "Big Data Technologien (Spark, Hadoop)" },
  { value: "business-analyse", label: "Business Analyse" },
  { value: "c-plus-plus", label: "C++" },
  { value: "c-sharp", label: "C#" },
  { value: "change-management", label: "Change Management" },
  { value: "ci-cd", label: "CI/CD (Jenkins, GitLab CI, GitHub Actions)" },
  { value: "cloud-basics", label: "Cloud Computing Grundlagen (AWS, Azure, GCP)" },
  { value: "crm-systems", label: "CRM-Systeme Allgemein" },
  { value: "css", label: "CSS" },
  { value: "cyber-security", label: "Cyber Security Grundlagen" },
  { value: "cypress", label: "Cypress" },
  { value: "data-analyse", label: "Datenanalyse Grundlagen" },
  { value: "data-visualization", label: "Datenvisualisierung (z.B. Tableau, Power BI)" },
  { value: "datenmodellierung", label: "Datenmodellierung" },
  { value: "django", label: "Django (Python)" },
  { value: "docker", label: "Docker" },
  { value: "erp-systems", label: "ERP-Systeme Allgemein" },
  { value: "excel-advanced", label: "Excel für Fortgeschrittene" },
  { value: "flask", label: "Flask (Python)" },
  { value: "flutter", label: "Flutter" },
  { value: "gcp-advanced", label: "GCP Vertiefung (Compute Engine, Cloud Storage etc.)" },
  { value: "git", label: "Git" },
  { value: "go", label: "Go" },
  { value: "html", label: "HTML" },
  { value: "it-consulting", label: "IT-Consulting Grundlagen" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "jest", label: "Jest" },
  { value: "jira", label: "Jira/Confluence" },
  { value: "junit-testng", label: "JUnit/TestNG" },
  { value: "kommunikation", label: "Kommunikationsfähigkeit" },
  { value: "kotlin", label: "Kotlin" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "linux", label: "Linux/Unix Grundlagen" },
  { value: "machine-learning", label: "Machine Learning Konzepte & Algorithmen" },
  { value: "mobile-dev-android", label: "Mobile Entwicklung Android (Kotlin/Java)" },
  { value: "mobile-dev-ios", label: "Mobile Entwicklung iOS (Swift)" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL Administration/Optimierung" },
  { value: "nextjs", label: "Next.js" },
  { value: "nodejs", label: "Node.js" },
  { value: "nosql", label: "NoSQL Datenbankkonzepte" },
  { value: "numpy", label: "NumPy" },
  { value: "pandas", label: "Pandas" },
  { value: "php", label: "PHP" },
  { value: "postgresql", label: "PostgreSQL Administration/Optimierung" },
  { value: "problemlösung", label: "Problemlösungskompetenz" },
  { value: "produktmanagement", label: "Produktmanagement Grundlagen" },
  { value: "projektmanagement", label: "Projektmanagement" },
  { value: "prozessmanagement", label: "Geschäftsprozessmanagement (BPMN)" },
  { value: "python", label: "Python" },
  { value: "pytorch", label: "PyTorch" },
  { value: "react", label: "React" },
  { value: "react-native", label: "React Native" },
  { value: "redis", label: "Redis" },
  { value: "requirements-engineering", label: "Requirements Engineering" },
  { value: "rust", label: "Rust" },
  { value: "salesforce", label: "Salesforce Grundlagen" },
  { value: "sap", label: "SAP Grundlagen / Module" },
  { value: "scikit-learn", label: "Scikit-learn" },
  { value: "selenium", label: "Selenium" },
  { value: "spring", label: "Spring Framework (Java)" },
  { value: "sql", label: "SQL" },
  { value: "svelte", label: "Svelte" },
  { value: "swift", label: "Swift" },
  { value: "teamarbeit", label: "Teamfähigkeit" },
  { value: "tensorflow", label: "TensorFlow" },
  { value: "terraform", label: "Terraform" },
  { value: "testing", label: "Software Testing Grundlagen" },
  { value: "typescript", label: "TypeScript" },
  { value: "ui-ux-basics", label: "UI/UX Design Grundlagenverständnis" },
  { value: "vuejs", label: "Vue.js" },
];